name: Integración Java Hola Mundo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio principal
      uses: actions/checkout@v4

    - name: Usar acción personalizada de gh-actions-library
      uses: danielgalvezpilco/gh-actions-library/java/deploy@main

    - name: Ejecutar workflow de tpl-job-cicd
      uses: danielgalvezpilco/tpl-job-cicd/.github/workflows/tpl-job-gradle.yml@main
